apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radosgw-ingressgateway-certs
  namespace: rook-ceph
spec:
  secretName: radosgw-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  commonName: rgw.argo.michaelgoldstein.co
  dnsNames:
    - rgw.argo.michaelgoldstein.co
    - '*.rgw.argo.michaelgoldstein.co'
