apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: auth-ingressgateway-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: auth.argo.michaelgoldstein.co
  dnsNames:
    - auth.argo.michaelgoldstein.co
