apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.2.0
    chart: keycloak
    helm:
     parameters:
      - name : auth.adminUser
        value : admin
      - name: auth.managementUser
        value: manager
      - name: proxyAddressForwarding
        value: "true"
      - name: auth.existingSecret
        value: keycloak-secret
      - name: postgresql.enabled
        value: "false"
      - name: externalDatabase.user
        value: "keycloak"
      - name: externalDatabase.database
        value: "keycloak"
      - name: externalDatabase.host
        value: keycloak-db
      - name: externalDatabase.existingSecret
        value: keycloak.keycloak-db.credentials.postgresql.acid.zalan.do
      - name: extraEnvVars[1].name
        value: KEYCLOAK_DATABASE_PASSWORD
      - name: extraEnvVars[1].valueFrom.secretKeyRef.name
        value: keycloak.keycloak-db.credentials.postgresql.acid.zalan.do
      - name: extraEnvVars[1].valueFrom.secretKeyRef.key
        value: password
      - name: extraEnvVars[2].name
        value: KEYCLOAK_DATABASE_HOST
      - name: extraEnvVars[2].value
        value: keycloak-db
      - name: extraEnvVars[3].name
        value: KEYCLOAK_DATABASE_NAME
      - name: extraEnvVars[3].value
        value: keycloak
      - name: extraEnvVars[4].name
        value: KEYCLOAK_DATABASE_USER
      - name: extraEnvVars[4].value
        value: keycloak
      - name: extraVolumeMounts[0].name
        value: config
      - name: extraVolumeMounts[0].mountPath
        value: "/config"
      - name: extraVolumeMounts[0].readOnly
        value: "true"
      - name: extraVolumes[0].name
        value: config
      - name: extraVolumes[0].secret.secretName
        value: kubeflow-realm
      - name: extraEnvVars[0].name
        value: KEYCLOAK_EXTRA_ARGS
      - name: extraEnvVars[0].value
        value: "-Dkeycloak.import=/config/kubeflow-realm.json"
      - name: service.type
        value: ClusterIP
      - name: service.port
        value: "8080"
      - name: service.httpsPort
        value: "8443"
      - name: metrics.enabled
        value: "true"
      - name: metrics.serviceMonitor.enabled
        value: "true"
      - name: metrics.serviceMonitor.namespace
        value: home
      - name: nodeSelector
        value: '"beta.kubernetes.io/arch": amd64'
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
