kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: grafana-admin-secret
  namespace: monitoring
  creationTimestamp: null
spec:
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
      creationTimestamp: null
    data: null
  encryptedData:
    admin-password: AgBt5/TXKEHzdHW403UjTxAt9XxrrncRJ2IQoUj+BpqQHkT0NHuQNUL4UIGcgX/JMja20tfUuAmcDQsneH5FGIgSq3XrPcr4e5l5gQdFGh7Y0fTYwAbGq/7aAed97u9FgttCCsib/GsBvJVHjasNbzD4KWtNP51xOEKiQjoJyBGn3xO5SkGJoydp3Pv1Vg4wR9gPH0GOyfZ+NgdX+6KOLfvvSxuakeY6Gh+v1dmAJAIP7WyJzLb9DTm+0UW7Tu1Q0bPfLfBcYqXXPfTNdKoU3bDJ3r5DI3fLjFN/99pk2+QOXBbo83qcLd7TTgl4erOael1TLpizUiVwl2DC19YSG17PwHRRe7YyH6rF9C7yf+Cx7GtQU86a46XzCJ0GeIjqxgv69vNHjmuLHpVOfUEB1HRIF1bYc0QDqYX6oZbpaQJPUbOYatAzWyx6hT+x4wmSGc2d2teGZ2FDYlII1vkQq7R5SHCR/IDKt+XgzGiZSkuha4S0xWRSHmFWZNBDHFLpx0HOwpNQxdNQOWIoDKWPjSdh87KQwRvCvzvKySFkwJOFJEDif2q7qdTnGvCCg17PbxC6wKyROwyfhC3owSOje8Ku4d0iuOfboqRf9UaURcVMc9IBKUtfYbGsIMEM4WPCZd0P3D9+y5YA7juSBUMCg6Ab4a7wqN952mCpfnGz34zz7AMTweU1UpyKIELeyb2ZzDIaBO92kEGeNQ==
    admin-user: AgBHG25VsYP3b8/asE5eLa5r5EC+3VV7LUY9Z+1qtWwG/V1CHJiz866a+24ZwYUsmpPfeEbX52lkIucpb/3H8qQIRMeTnKqSDfnJIS9Hd2p2yzOyMr+rBNYqEUjtQVt7l+yQoTc1CsEyIdi3Qm48rbYxY2TmbzIhNLkXaJUTa2tUQgKu99ilwkj+4VN3HxAfE4eo0+/SxEakicqu/gPKee9fD8wI9+mItrD+5FE6LNqzFHWUgTlJoFfb5leyDSfBvb1Ete4W17/buyqGhPgXFDDhsXsP6Miw8dQ35soHkCYLEvpKesEjHsJ7kkeCBEWdYI0KcxZTgRG8VhiNB+uER/sYtmNkQqswdPcpbizoNW7wwwTxj7Z18cJ9VAeQnKe2U8PBZ7y1dEuENHJGGwnt77EvlZJjjxQlKeZWgDzUPWEN2AWQNv/GjhiFJlQhzTkFdBQW22TZBhJ3sb7LwIQSdMo8MDLaCQ+NA+OcbU2xOGkvcMtHTdkX/eCbn+oVdRC+Vz8hiUeADS5Iz4eeH4AjVPAoJUk2a7xcDwnZ7KwrR55otGcNMh8C2czyxRBcOxbtH+60qrIzek3xh6m6emVNE2w14/KHL8FC1FdxMBcKbWsCRyKfArMKLB1mehcEBvUsCgpxXeee8JdpxLlnHPaF+/xQgJxygunD+WSnlUkAx0FsVP+DwndI9QRLv4rpXgZiAt+R6XQvF961
